---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  Exclude:
    - lib/test.rb

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile

Metrics/MethodLength:
  ExcludedMethods: ['build_entity']

# allow unsafe YAML loading in test code only
Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Lint/NonDeterministicRequireOrder:
  Enabled: true
  Exclude:
    - "**/init.rb"

Style/HashLikeCase:
  MinBranchesCount: 5

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - Rakefile
