---
development:
  # Application
  APP_HOST: http://localhost:9000

test:
  # Application
  APP_HOST: http://localhost:9000
  # Api
  API_HOST: http://localhost:9090

production:
  # Infrastructure
  API_HOST: https://drinkking-api.herokuapp.com
